### ISSUE TITLE
显存问题

### ISSUE THREAD

**Issue by upccpu** [Link-Li/CLMLF#2]
您好，我有个问题比较困惑。为什么在训练时显存使用在逐渐增多？您训练时使用的显存是多少？

**Comment by upccpu** [comment]
抱歉，我看到了文章里使用了4块3090.我还是没琢磨明白显存增加的问题？是因为有预训练么？

**Comment by Link-Li** [comment]
我在训练的过程中没有发现显存逐渐增加的问题，你看一下使用的python包的版本是否一致

**Comment by upccpu** [comment]
> 我在训练的过程中没有发现显存逐渐增加的问题，你看一下使用的python包的版本是否一致

好的，感谢回复！我跑了几遍发现应该是每一个批次数据大小不一致导致的显存波动，其实并没有持续增加。
